# Generated by Django 2.2 on 2020-07-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('authority_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=350)),
                ('token', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('booth_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=350)),
                ('total_collection', models.CharField(default='0', max_length=100)),
                ('token', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('authority_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=350)),
                ('token', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('plaza_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=100)),
                ('total_collection', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('authority_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('contract_duration', models.CharField(max_length=100)),
                ('contract_amount', models.FloatField(default=0)),
                ('collected_amount', models.FloatField(default=0)),
                ('road_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('authority_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('user_type', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=350)),
                ('token', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_id', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=0)),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vehicle_id', models.CharField(default='', max_length=100)),
                ('vehicle_type', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Authority')),
                ('booth_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Booth')),
                ('plaza_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Plaza')),
                ('road_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Road')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_rate', models.FloatField(default=0)),
                ('lcv_rate', models.FloatField(default=0)),
                ('truck_rate', models.FloatField(default=0)),
                ('bus_rate', models.FloatField(default=0)),
                ('plaza_id', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Plaza')),
            ],
        ),
        migrations.AddField(
            model_name='plaza',
            name='road_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Road'),
        ),
        migrations.AddField(
            model_name='booth',
            name='plaza_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Plaza'),
        ),
        migrations.AddField(
            model_name='booth',
            name='road_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testing.Road'),
        ),
    ]
